### ISSUE TITLE
Please support additional options / subdirectories

### ISSUE THREAD

**Issue by dhoppe** [kernelold/pre-commit-packer#1]
@kernelold Could you please extend the script ```packer-validate.sh``` to make sure that the pre-commit hook supports ```-var-file``` and subdirectories?

I have a directory structure like this and would like to be able to validate different operating systems or releases:
```
dhoppe at mac-mini in packer-vmware-iso on  main [+?]
❯ tree
.
├── LICENSE
├── README.md
└── ubuntu
   ├── builds.pkr.hcl
   ├── data
   │  ├── meta-data
   │  └── user-data
   ├── sources.pkr.hcl
   ├── ubuntu-22.04.pkrvars.hcl
   ├── ubuntu.auto.pkrvars.hcl
   ├── variables.pkr.hcl
   └── versions.pkr.hcl
```

**Comment by kernelold** [comment]
fixed in 0.0.12
